// ============================================
// AssistMint — WhatsApp Payments (India)
// ============================================
// Native in-chat UPI invoices: interactive `order_details` messages (paid
// with WhatsApp Pay UPI or any UPI app on the device) and `order_status`
// messages that update the invoice in place. Works with the UPI-intent mode
// (Cashfree, Billdesk, CCAvenue) and the payment-gateway deep-integration
// mode (Razorpay, PayU, Billdesk, Zaakpay).
//
// Amounts use the Payments API `{ value, offset }` object: offset is always
// 100 for INR and `value` is the amount in paise (₹210.00 → 21000).
//
// NOTE: `order_details` / `order_status` require the WABA to be onboarded to
// WhatsApp Payments India (a Meta onboarding — email
// whatsappindia-bizpayments-support@meta.com, see research doc §2.3). On a
// non-onboarded WABA Meta rejects the message type outright (HTTP 400, code
// 131009 "Unsupported Interactive Message type"). sendPayCtaMessage below is
// the onboarding-free fallback: a tappable button that opens the payment page.
//
// Docs: https://developers.facebook.com/documentation/business-messaging/whatsapp/payments/payments-in/overview

import { sanitizeWhatsAppNumber } from './client';
import { extractMessageId, graphRequest } from './shared';
import type { MessageSendEnvelope, MessageTarget, PaymentAmount } from './types';

/** Offset for INR amounts (value is in paise). */
const INR_OFFSET = 100;

/** Amount in paise → Payments API amount object. */
function paise(valueInPaise: number): PaymentAmount {
  if (!Number.isInteger(valueInPaise) || valueInPaise < 0) {
    throw new Error(`Invalid amount (expected a non-negative integer in paise): ${valueInPaise}`);
  }
  return { value: valueInPaise, offset: INR_OFFSET };
}

// ─── Types ──────────────

/** Order status values for `order_status` messages (`pending` only appears in order_details). */
export type OrderStatus =
  | 'pending'
  | 'processing'
  | 'partially_shipped'
  | 'shipped'
  | 'completed'
  | 'canceled';

/** Payment status relayed to the customer via `order_status` messages. */
export type PaymentStatus = 'pending' | 'captured' | 'failed';

/** Supported payment gateways for the deep-integration mode. */
export type PaymentGatewayType = 'razorpay' | 'payu' | 'billdesk' | 'zaakpay';

/** Importer address required on physical-goods items without a catalog id. */
export interface ImporterAddress {
  addressLine1: string;
  addressLine2?: string;
  city: string;
  zoneCode?: string;
  postalCode?: string;
  countryCode: string;
}

/** One line item on an order. */
export interface OrderItem {
  /** Display name (max 60 chars). */
  name: string;
  /** Per-item price in paise (₹100.00 → 10000). */
  amountInPaise: number;
  quantity: number;
  /** Optional catalog retailer id — links the line to a catalog item. */
  retailerId?: string;
  /** Discounted per-item price in paise (must be lower than amount). */
  saleAmountInPaise?: number;
  /** Required for physical goods when no catalog id is used. */
  countryOfOrigin?: string;
  /** Required for physical goods when no catalog id is used. */
  importerName?: string;
  /** Required for physical goods when no catalog id is used. */
  importerAddress?: ImporterAddress;
}

/** Payment-gateway deep-integration configuration. */
export interface PaymentGatewayConfig {
  gatewayType: PaymentGatewayType;
  /** Payment configuration id created in Business Manager. */
  configurationName: string;
  /** Gateway-specific passthrough params (udf1-4 for PayU, receipt/notes for Razorpay, extra1-2 for Zaakpay). */
  extraParams?: Record<string, string>;
}

/** How the customer pays: a UPI intent link from your PG (Cashfree) or a payment gateway config. */
export interface OrderPaymentConfig {
  /** Full `upi://pay?...` intent link generated by your payment gateway. */
  upiIntentLink?: string;
  /** Payment gateway deep-integration configuration. */
  paymentGateway?: PaymentGatewayConfig;
}

/** Expiration shown on the order bubble (UTC timestamp in seconds as a string). */
export interface OrderExpiration {
  timestamp: string;
  description?: string;
}

// ─── UPI intent link builder ──────────────

/** Parameters for {@link buildUpiIntentLink}. */
export interface UpiIntentParams {
  /** Merchant virtual payment address, e.g. `assistmint@upi`. */
  vpa: string;
  /** Payee (business) name. */
  payeeName: string;
  /** Amount in paise (₹250.00 → 25000). */
  amountInPaise?: number;
  /** Currency, default INR. */
  currency?: string;
  /** Note shown in the UPI app. */
  note?: string;
  /** Transaction reference (maps the payment back to your order). */
  transactionRef?: string;
  /** Merchant category code. */
  mcc?: string;
  /** Purpose code. */
  purposeCode?: string;
}

/**
 * Build a UPI intent link: `upi://pay?pa=<vpa>&pn=<name>&am=<amount>&cu=INR&tn=<note>`.
 * Spaces are percent-encoded (UPI apps reject `+`).
 *
 * Note: WhatsApp's order_details `upi_intent_link` payment settings only
 * pass through the `pa`, `pn`, `mc`, `purpose` and `tr` attributes — amount
 * and note are shown from the order message itself.
 *
 * Docs: https://developers.facebook.com/documentation/business-messaging/whatsapp/payments/payments-in/upi-intent/dynamic-vpa
 */
export function buildUpiIntentLink(params: UpiIntentParams): string {
  const search = new URLSearchParams();
  search.set('pa', params.vpa);
  search.set('pn', params.payeeName);
  if (params.amountInPaise !== undefined) {
    search.set('am', (params.amountInPaise / 100).toFixed(2));
  }
  search.set('cu', params.currency ?? 'INR');
  if (params.note !== undefined) search.set('tn', params.note);
  if (params.transactionRef !== undefined) search.set('tr', params.transactionRef);
  if (params.mcc !== undefined) search.set('mc', params.mcc);
  if (params.purposeCode !== undefined) search.set('purpose', params.purposeCode);
  return `upi://pay?${search.toString().replace(/\+/g, '%20')}`;
}

// ─── order_details message ──────────────

export interface SendOrderDetailsMessageOptions extends MessageTarget {
  /** Your id for this order/transaction — payment status webhooks arrive against it. */
  referenceId: string;
  items: OrderItem[];
  /**
   * Total in paise. Must equal subtotal + tax + shipping − discount.
   * Computed automatically from the items when omitted.
   */
  totalAmountInPaise?: number;
  taxInPaise?: number;
  shippingInPaise?: number;
  discountInPaise?: number;
  /** Currency code — only INR is supported today. Default: 'INR'. */
  currency?: string;
  /** Exactly one of `upiIntentLink` or `paymentGateway` is required. */
  paymentConfig: OrderPaymentConfig;
  bodyText?: string;
  /** Optional thumbnail for the invoice (image header). */
  headerImageUrl?: string;
  footerText?: string;
  /** 'digital-goods' (default, services/food) or 'physical-goods' (requires importer details). */
  goodsType?: 'digital-goods' | 'physical-goods';
  expiration?: OrderExpiration;
}

/**
 * Send an interactive `order_details` message — a native in-chat invoice the
 * customer pays without leaving WhatsApp (WhatsApp Pay UPI or any installed
 * UPI app). Build the `upiIntentLink` from your PG (Cashfree) or pass a
 * `paymentGateway` config for the deep-integration mode.
 *
 * Docs: https://developers.facebook.com/documentation/business-messaging/whatsapp/payments/payments-in/upi-intent/dynamic-vpa
 */
export async function sendOrderDetailsMessage(
  options: SendOrderDetailsMessageOptions
): Promise<{ message_id: string }> {
  const {
    phoneNumberId,
    accessToken,
    to,
    referenceId,
    items,
    totalAmountInPaise,
    taxInPaise = 0,
    shippingInPaise = 0,
    discountInPaise = 0,
    currency = 'INR',
    paymentConfig,
    bodyText,
    headerImageUrl,
    footerText,
    goodsType = 'digital-goods',
    expiration,
  } = options;

  if (items.length === 0) {
    throw new Error('sendOrderDetailsMessage: at least one order item is required');
  }
  if ((paymentConfig.upiIntentLink ? 1 : 0) + (paymentConfig.paymentGateway ? 1 : 0) !== 1) {
    throw new Error('sendOrderDetailsMessage: provide exactly one of paymentConfig.upiIntentLink or paymentConfig.paymentGateway');
  }

  const gateway = paymentConfig.paymentGateway;

  // Payment settings — one entry, either a UPI intent link or a payment gateway.
  let paymentSettings: Record<string, unknown>[];
  if (paymentConfig.upiIntentLink) {
    paymentSettings = [
      {
        type: 'upi_intent_link',
        upi_intent_link: { link: paymentConfig.upiIntentLink },
      },
    ];
  } else if (gateway) {
    paymentSettings = [
      {
        type: 'payment_gateway',
        payment_gateway: {
          type: gateway.gatewayType,
          configuration_name: gateway.configurationName,
          ...(gateway.extraParams ? { [gateway.gatewayType]: gateway.extraParams } : {}),
        },
      },
    ];
  } else {
    throw new Error(
      'sendOrderDetailsMessage: provide exactly one of paymentConfig.upiIntentLink or paymentConfig.paymentGateway'
    );
  }

  // Amounts — subtotal is derived from the items; total must satisfy
  // subtotal + tax + shipping − discount.
  const subtotal = items.reduce((sum, item) => sum + item.amountInPaise * item.quantity, 0);
  const expectedTotal = subtotal + taxInPaise + shippingInPaise - discountInPaise;
  if (totalAmountInPaise !== undefined && totalAmountInPaise !== expectedTotal) {
    throw new Error(
      `sendOrderDetailsMessage: totalAmountInPaise (${totalAmountInPaise}) must equal subtotal + tax + shipping − discount (${expectedTotal})`
    );
  }

  const order: Record<string, unknown> = {
    status: 'pending',
    items: items.map((item) => ({
      name: item.name.substring(0, 60),
      amount: paise(item.amountInPaise),
      quantity: item.quantity,
      ...(item.retailerId ? { retailer_id: item.retailerId } : {}),
      ...(item.saleAmountInPaise !== undefined ? { sale_amount: paise(item.saleAmountInPaise) } : {}),
      ...(item.countryOfOrigin ? { country_of_origin: item.countryOfOrigin } : {}),
      ...(item.importerName ? { importer_name: item.importerName } : {}),
      ...(item.importerAddress
        ? {
            importer_address: {
              address_line1: item.importerAddress.addressLine1,
              ...(item.importerAddress.addressLine2
                ? { address_line2: item.importerAddress.addressLine2 }
                : {}),
              city: item.importerAddress.city,
              ...(item.importerAddress.zoneCode ? { zone_code: item.importerAddress.zoneCode } : {}),
              ...(item.importerAddress.postalCode ? { postal_code: item.importerAddress.postalCode } : {}),
              country_code: item.importerAddress.countryCode,
            },
          }
        : {}),
    })),
    subtotal: paise(subtotal),
    tax: paise(taxInPaise),
    ...(shippingInPaise > 0 ? { shipping: paise(shippingInPaise) } : {}),
    ...(discountInPaise > 0 ? { discount: paise(discountInPaise) } : {}),
    ...(expiration ? { expiration } : {}),
  };

  const interactive: Record<string, unknown> = {
    type: 'order_details',
    ...(headerImageUrl ? { header: { type: 'image', image: { link: headerImageUrl } } } : {}),
    body: { text: (bodyText ?? 'Please review your order and complete the payment.').substring(0, 1024) },
    ...(footerText ? { footer: { text: footerText.substring(0, 60) } } : {}),
    action: {
      name: 'review_and_pay',
      parameters: {
        reference_id: referenceId,
        type: goodsType,
        payment_settings: paymentSettings,
        currency,
        total_amount: paise(totalAmountInPaise ?? expectedTotal),
        order,
      },
    },
  };

  const data = await graphRequest<MessageSendEnvelope>({
    path: `${phoneNumberId}/messages`,
    accessToken,
    method: 'POST',
    body: {
      messaging_product: 'whatsapp',
      recipient_type: 'individual',
      to: sanitizeWhatsAppNumber(to),
      type: 'interactive',
      interactive,
    },
  });
  return { message_id: extractMessageId(data) };
}

// ─── order_status message ──────────────

export interface SendOrderStatusMessageOptions extends MessageTarget {
  /** The same reference id used in the original order_details message. */
  referenceId: string;
  /**
   * New order status. Status transitions are validated by Meta: `pending`
   * can move to any status; `processing`/`shipped`/`partially_shipped` are
   * interchangeable; `completed` and `canceled` are terminal. Error codes
   * 2046 (invalid transition) and 2047 (cannot cancel a paid order) come
   * back via webhook.
   */
  status: Exclude<OrderStatus, 'pending'>;
  /** Optional status text shown on the order details page (max 120 chars, useful for cancellations). */
  description?: string;
  /** Optional payment signal relayed to the customer ('captured' shows a paid label with a green checkmark). */
  paymentStatus?: PaymentStatus;
  /** Epoch seconds for the payment status. */
  paymentTimestamp?: number;
  bodyText?: string;
  footerText?: string;
}

/**
 * Send an interactive `order_status` message — updates the customer's
 * original order_details invoice in place (pending → processing → completed
 * etc.). Always send after receiving a payment signal from your PG so the
 * invoice reflects reality.
 *
 * Docs: https://developers.facebook.com/documentation/business-messaging/whatsapp/payments/payments-in/upi-intent/dynamic-vpa
 */
export async function sendOrderStatusMessage(
  options: SendOrderStatusMessageOptions
): Promise<{ message_id: string }> {
  const {
    phoneNumberId,
    accessToken,
    to,
    referenceId,
    status,
    description,
    paymentStatus,
    paymentTimestamp,
    bodyText,
    footerText,
  } = options;

  const interactive: Record<string, unknown> = {
    type: 'order_status',
    body: { text: (bodyText ?? 'Update on your order.').substring(0, 1024) },
    ...(footerText ? { footer: { text: footerText.substring(0, 60) } } : {}),
    action: {
      name: 'review_order',
      parameters: {
        reference_id: referenceId,
        order: {
          status,
          ...(description ? { description: description.substring(0, 120) } : {}),
        },
        ...(paymentStatus
          ? {
              payment: {
                status: paymentStatus,
                ...(paymentTimestamp !== undefined ? { timestamp: paymentTimestamp } : {}),
              },
            }
          : {}),
      },
    },
  };

  const data = await graphRequest<MessageSendEnvelope>({
    path: `${phoneNumberId}/messages`,
    accessToken,
    method: 'POST',
    body: {
      messaging_product: 'whatsapp',
      recipient_type: 'individual',
      to: sanitizeWhatsAppNumber(to),
      type: 'interactive',
      interactive,
    },
  });
  return { message_id: extractMessageId(data) };
}

// ─── cta_url message (payments onboarding fallback) ──────────────

export interface SendPayCtaMessageOptions extends MessageTarget {
  /** Body text shown above the button (max 1024 chars). */
  bodyText: string;
  /**
   * Button label. Truncated to 20 chars — the tightest documented CTA
   * button-text limit, so any label survives Meta's validation.
   */
  buttonText: string;
  /** URL opened when the button is tapped (e.g. the Cashfree payment page, which itself offers UPI intent on mobile). */
  url: string;
}

/**
 * Send an interactive `cta_url` message — a plain text message with a single
 * tappable call-to-action button that opens `url` (the payment gateway page,
 * which offers UPI/card on mobile). Unlike {@link sendOrderDetailsMessage}
 * this works on ANY WABA — no WhatsApp Payments India onboarding required —
 * making it the graceful fallback when the native `order_details` invoice is
 * rejected (HTTP 400, code 131009: "Unsupported Interactive Message type").
 *
 * Docs: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages
 */
export async function sendPayCtaMessage(
  options: SendPayCtaMessageOptions
): Promise<{ message_id: string }> {
  const { phoneNumberId, accessToken, to, bodyText, buttonText, url } = options;

  const interactive: Record<string, unknown> = {
    type: 'cta_url',
    body: { text: bodyText.substring(0, 1024) },
    action: {
      name: 'cta_url',
      parameters: [
        {
          display_text: buttonText.substring(0, 20),
          url,
        },
      ],
    },
  };

  const data = await graphRequest<MessageSendEnvelope>({
    path: `${phoneNumberId}/messages`,
    accessToken,
    method: 'POST',
    body: {
      messaging_product: 'whatsapp',
      recipient_type: 'individual',
      to: sanitizeWhatsAppNumber(to),
      type: 'interactive',
      interactive,
    },
  });
  return { message_id: extractMessageId(data) };
}

// ─── Webhook parsers ──────────────

/** Narrow unknown values safely (no `any`). */
function asRecord(value: unknown): Record<string, unknown> | null {
  return typeof value === 'object' && value !== null ? (value as Record<string, unknown>) : null;
}

function asNumber(value: unknown): number | undefined {
  return typeof value === 'number' ? value : undefined;
}

function asString(value: unknown): string | undefined {
  return typeof value === 'string' ? value : undefined;
}

/** A transaction attempt inside a payment status webhook. */
export interface PaymentTransaction {
  /** Payment gateway order id. */
  id: string;
  pgTransactionId?: string;
  type?: string;
  status: 'pending' | 'success' | 'failed' | string;
  createdTimestamp?: number;
  updatedTimestamp?: number;
  amount?: PaymentAmount;
  orderAmount?: PaymentAmount;
  currency?: string;
  method?: { type?: string };
  error?: { code?: string; reason?: string };
  refunds?: Array<Record<string, unknown>>;
}

/** Parsed payment status webhook event (one per reference_id). */
export interface PaymentWebhookEvent {
  referenceId: string;
  status: 'pending' | 'captured' | string;
  amount?: PaymentAmount;
  currency?: string;
  transactions: PaymentTransaction[];
}

function parseAmount(value: unknown): PaymentAmount | undefined {
  const record = asRecord(value);
  if (!record) return undefined;
  const amountValue = asNumber(record.value);
  const offset = asNumber(record.offset);
  if (amountValue === undefined || offset === undefined) return undefined;
  return { value: amountValue, offset };
}

function parseTransaction(value: unknown): PaymentTransaction {
  const record = asRecord(value) ?? {};
  const method = asRecord(record.method);
  const error = asRecord(record.error);
  return {
    id: asString(record.id) ?? '',
    pgTransactionId: asString(record.pg_transaction_id),
    type: asString(record.type),
    status: asString(record.status) ?? 'pending',
    createdTimestamp: asNumber(record.created_timestamp),
    updatedTimestamp: asNumber(record.updated_timestamp),
    amount: parseAmount(record.amount),
    orderAmount: parseAmount(record.order_amount),
    currency: asString(record.currency),
    ...(method ? { method: { type: asString(method.type) } } : {}),
    ...(error ? { error: { code: asString(error.code), reason: asString(error.reason) } } : {}),
    ...(Array.isArray(record.refunds) ? { refunds: record.refunds.map((r) => (asRecord(r) ?? {})) } : {}),
  };
}

/**
 * Parse a payment status webhook body (`entry[].changes[].value.payments[]`)
 * into typed events. Fires when the PG reports a payment attempt against a
 * `reference_id` you sent in an order_details message. Pair with
 * `sendOrderStatusMessage` to relay the outcome to the customer.
 *
 * Docs: https://developers.facebook.com/documentation/business-messaging/whatsapp/payments/payments-in/pg
 */
export function parsePaymentWebhook(body: unknown): PaymentWebhookEvent[] {
  const events: PaymentWebhookEvent[] = [];
  const root = asRecord(body);
  const entries = Array.isArray(root?.entry) ? (root?.entry as unknown[]) : [];

  for (const entryValue of entries) {
    const entry = asRecord(entryValue);
    const changes = Array.isArray(entry?.changes) ? (entry?.changes as unknown[]) : [];
    for (const changeValue of changes) {
      const change = asRecord(changeValue);
      const value = asRecord(change?.value);
      const payments = Array.isArray(value?.payments) ? (value?.payments as unknown[]) : [];
      for (const paymentValue of payments) {
        const payment = asRecord(paymentValue);
        if (!payment) continue;
        events.push({
          referenceId: asString(payment.reference_id) ?? '',
          status: asString(payment.status) ?? 'pending',
          amount: parseAmount(payment.amount),
          currency: asString(payment.currency),
          transactions: Array.isArray(payment.transactions)
            ? (payment.transactions as unknown[]).map(parseTransaction)
            : [],
        });
      }
    }
  }

  return events;
}

/** One product line of a cart order webhook. */
export interface OrderWebhookProductItem {
  productRetailerId: string;
  quantity: number;
  itemPrice?: number;
  currency?: string;
}

/** Parsed cart-order webhook event (customer sent a cart/order from the catalog). */
export interface OrderWebhookEvent {
  catalogId?: string;
  text?: string;
  productItems: OrderWebhookProductItem[];
}

/**
 * Parse an order webhook body (`entry[].changes[].value.order`) — the cart
 * order a customer sends after browsing your catalog — into typed events
 * with products, quantities and prices.
 *
 * Docs: https://developers.facebook.com/documentation/business-messaging/whatsapp/catalogs/sell-products-and-services/receiving-responses
 */
export function parseOrderWebhook(body: unknown): OrderWebhookEvent[] {
  const events: OrderWebhookEvent[] = [];
  const root = asRecord(body);
  const entries = Array.isArray(root?.entry) ? (root?.entry as unknown[]) : [];

  for (const entryValue of entries) {
    const entry = asRecord(entryValue);
    const changes = Array.isArray(entry?.changes) ? (entry?.changes as unknown[]) : [];
    for (const changeValue of changes) {
      const change = asRecord(changeValue);
      const value = asRecord(change?.value);
      const order = asRecord(value?.order);
      if (!order) continue;

      const rawItems = Array.isArray(order.product_items) ? (order.product_items as unknown[]) : [];
      events.push({
        catalogId: asString(order.catalog_id),
        text: asString(order.text),
        productItems: rawItems
          .map((itemValue) => {
            const item = asRecord(itemValue);
            if (!item) return null;
            const retailerId = asString(item.product_retailer_id);
            if (retailerId === undefined) return null;
            const orderWebhookItem: OrderWebhookProductItem = {
              productRetailerId: retailerId,
              quantity: asNumber(item.quantity) ?? 1,
              itemPrice: asNumber(item.item_price),
              currency: asString(item.currency),
            };
            return orderWebhookItem;
          })
          .filter((item): item is OrderWebhookProductItem => item !== null),
      });
    }
  }

  return events;
}
