-- ⚠️ DEPRECATED — DO NOT USE
-- The Supabase database is the source of truth.
-- Schema changes are managed directly in the Supabase Dashboard or via MCP.
-- This file is kept only as historical reference.
-- Last verified via Supabase MCP on 2026-05-21.
